import * as Print from "expo-print";
import * as FileSystem from "expo-file-system/legacy";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  formatCurrency,
  formatMonthYear,
  getMonthStart,
  getMonthEnd,
} from "./dateUtils";
import {
  getTotalIncome,
  getTotalExpenses,
  getNetSavings,
  getSavingsRate,
  getCategoryTotals,
  getSourceTotals,
} from "./calculationUtils";

const LAST_EXPORT_KEY = "@fintracker_last_export";

function getCurrentMonthYear() {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
}

function isLastDaysOfMonth(daysBeforeEnd = 3) {
  const now = new Date();
  const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0);
  const diff = lastDay.getDate() - now.getDate();
  return diff >= 0 && diff <= daysBeforeEnd;
}

export async function checkAndRunAutoExport(
  transactions,
  settings
) {
  if (!settings.autoExport) return false;

  const monthYear = getCurrentMonthYear();
  if (!isLastDaysOfMonth()) return false;

  const lastExport = await AsyncStorage.getItem(LAST_EXPORT_KEY);
  if (lastExport === monthYear) return false;

  await runExport(transactions, monthYear);
  await AsyncStorage.setItem(LAST_EXPORT_KEY, monthYear);
  return true;
}

export async function getLastExportMonth() {
  return await AsyncStorage.getItem(LAST_EXPORT_KEY);
}

async function runExport(transactions, monthYear) {
  const [year, month] = monthYear.split("-").map(Number);
  const monthStart = getMonthStart(monthYear);
  const monthEnd = getMonthEnd(monthYear);
  const monthLabel = formatMonthYear(year, month);

  const monthlyIncome = getTotalIncome(transactions, monthStart, monthEnd);
  const monthlyExpenses = getTotalExpenses(transactions, monthStart, monthEnd);
  const monthlySavings = getNetSavings(transactions, monthStart, monthEnd);
  const monthlySavingsRate = getSavingsRate(transactions, monthStart, monthEnd);
  const categoryTotals = getCategoryTotals(transactions, monthStart, monthEnd);
  const sourceTotals = getSourceTotals(transactions, monthStart, monthEnd);

  const incomeRows = Object.entries(sourceTotals)
    .map(
      ([source, amount]) =>
        `<tr><td>${source}</td><td style="text-align:right;color:#10b981">${formatCurrency(amount)}</td></tr>`
    )
    .join("");

  const expenseRows = Object.entries(categoryTotals)
    .map(
      ([cat, amount]) =>
        `<tr><td>${cat}</td><td style="text-align:right;color:#ef4444">${formatCurrency(amount)}</td></tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body { font-family: 'Helvetica', Arial, sans-serif; padding: 30px; color: #111827; }
h1 { color: #14b8a6; font-size: 24px; margin-bottom: 5px; }
h2 { color: #111827; font-size: 18px; margin-top: 20px; border-bottom: 2px solid #14b8a6; }
.subtitle { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
.summary-grid { display: flex; flex-wrap: wrap; gap: 10px; margin: 15px 0; }
.summary-card { flex: 1; min-width: 120px; padding: 12px; background: #f9fafb; border-radius: 8px; border: 1px solid #e5e7eb; }
.summary-card .label { font-size: 12px; color: #6b7280; }
.summary-card .value { font-size: 18px; font-weight: bold; margin-top: 4px; }
table { width: 100%; border-collapse: collapse; margin: 10px 0; }
th { background: #14b8a6; color: white; padding: 8px; text-align: left; font-size: 13px; }
td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
.footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; text-align: center; }
</style></head><body>
<h1>FinTracker Pro</h1>
<div class="subtitle">Auto-Generated Report - ${monthLabel}</div>
<h2>Monthly Summary</h2>
<div class="summary-grid">
<div class="summary-card"><div class="label">Total Income</div><div class="value" style="color:#10b981">${formatCurrency(monthlyIncome)}</div></div>
<div class="summary-card"><div class="label">Total Expenses</div><div class="value" style="color:#ef4444">${formatCurrency(monthlyExpenses)}</div></div>
<div class="summary-card"><div class="label">Net Savings</div><div class="value" style="color:${monthlySavings >= 0 ? "#10b981" : "#ef4444"}">${formatCurrency(monthlySavings)}</div></div>
<div class="summary-card"><div class="label">Savings Rate</div><div class="value" style="color:#14b8a6">${monthlySavingsRate}%</div></div>
</div>
<h2>Income Breakdown</h2>
<table><tr><th>Source</th><th style="text-align:right">Amount</th></tr>${incomeRows || "<tr><td colspan='2' style='text-align:center'>No income</td></tr>"}</table>
<h2>Expense Breakdown</h2>
<table><tr><th>Category</th><th style="text-align:right">Amount</th></tr>${expenseRows || "<tr><td colspan='2' style='text-align:center'>No expenses</td></tr>"}</table>
<div class="footer">Generated by FinTracker Pro on ${new Date().toLocaleDateString()} | Auto-export</div>
</body></html>`;

  const { base64 } = await Print.printToFileAsync({ html, base64: true });
  const pdfName = `FinTracker_Report_${monthLabel.replace(" ", "")}.pdf`;

  const dirUri = await AsyncStorage.getItem("@fintracker_export_dir");
  let saved = false;
  if (dirUri && FileSystem.StorageAccessFramework) {
    try {
      const fileUri = await FileSystem.StorageAccessFramework.createFileAsync(
        dirUri,
        pdfName.replace(".pdf", ""),
        "application/pdf"
      );
      await FileSystem.writeAsStringAsync(fileUri, base64, {
        encoding: FileSystem.EncodingType.Base64,
      });
      saved = true;
    } catch {
      // SAF write failed, fall back below
    }
  }
  if (!saved) {
    const dest = FileSystem.documentDirectory + pdfName;
    await FileSystem.writeAsStringAsync(dest, base64, {
      encoding: FileSystem.EncodingType.Base64,
    });
  }
}
